sudo: false
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.8
    - libopencv-dev

script:
  - cmake .
  - make
  - runUnitTests
